MODEL:
  # ARCH: Hendrycks2020AugMix_ResNeXt_swa
  ARCH: Hendrycks2020AugMix_ResNeXt

DATA_DIR: "./datasets"

INPUT:
  SIZE: 
    - 32 
    - 32

TEST:
  BATCH_SIZE: 64

OPTIM:
  LR: 1e-3

CORRUPTION:
  DATASET: cifar100
  NUM_CLASS: 100
  SEVERITY:
    - 5
  TYPE:
    - brightness
    - glass_blur
    - jpeg_compression
    - contrast
    - defocus_blur
    - impulse_noise
    - motion_blur
    - snow
    - zoom_blur
    - frost
    - pixelate
    - gaussian_noise
    - elastic_transform
    - shot_noise
    - fog