OPTIM:
  METHOD: Adam
  STEPS: 1
  BETA: 0.9
  WD: 0.

ADAPTER:
  NAME: bosa
  BOSA:
   EMA_DECAY: 0.999 # 0.999 for CIFAR10, CIFAR100 0.99 for ImageNet-C
   MEMORY_SIZE: 64
   UPDATE_FREQUENCY: 64
   LAMBDA_T: 100.0
   LAMBDA_U: 1.0
